name: astrodetnv
channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda
  - https://ftp.osuosl.org/pub/open-ce/1.5.1
  - conda-forge
  - https://ftp.osuosl.org/pub/open-ce/1.8.0/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=2.0=cuda_2
  - _tensorflow_select=2.0=cuda_2
  - abseil-cpp=20210324.2=h3b9df90_0
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py39h9ca6cee_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alembic=1.7.7=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha810350_1
  - arrow-cpp=5.0.0=py39ha9c67ab_3_cpu
  - asdf=2.7.2=pyhd8ed1ab_0
  - asn1crypto=1.5.1=pyhd8ed1ab_0
  - astropy=5.0.4=py39hfc2be9b_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - av=8.0.3=py39h2698049_3
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=openblas
  - bleach=5.0.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - blosc=1.21.1=h8f22095_0
  - bokeh=2.3.3=py39h6ffa863_0
  - bottleneck=1.3.4=py39h4e7300c_0
  - brotli=1.0.9=hb283c62_7
  - brotli-bin=1.0.9=hb283c62_7
  - brotlipy=0.7.0=py39ha810350_1003
  - brunsli=0.1=h3b9df90_0
  - bzip2=1.0.8=h4e0d66e_4
  - c-ares=1.18.1=h4e0d66e_0
  - ca-certificates=2022.9.24=h1084571_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h95f367f_1001
  - catalogue=2.0.6=py39hc1b9086_1
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.14.6=py39hf9d8e4b_0
  - cfitsio=3.470=hf0d0db6_6
  - cftime=1.5.1.1=py39hfc2be9b_0
  - chardet=4.0.0=py39hc1b9086_3
  - charls=2.2.0=h29c3540_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - clang=10.0.1=default_hc9b7fb1_0
  - click=8.0.4=py39hc1b9086_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorcet=3.0.0=py39h6ffa863_0
  - conda-package-handling=1.8.1=py39h9ca6cee_0
  - configparser=5.2.0=pyhd8ed1ab_0
  - cryptography=36.0.2=py39hd4ec19a_1
  - cudatoolkit=11.2.2=hc16615c_9
  - cudnn=8.1.1_11.2=h5ec40c6_1
  - curl=7.82.0=h2ae36b4_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cymem=2.0.6=py39had50986_2
  - cython-blis=0.7.7=py39h4e7300c_0
  - cytoolz=0.11.2=py39h9ca6cee_2
  - dali=1.9.0=h2805ddd_cuda11.2_py39_pb3.14_2
  - dask=2022.2.1=pyhd3eb1b0_0
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - databricks-cli=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py39h6ffa863_1
  - debugpy=1.5.1=py39had50986_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.4=pyhd8ed1ab_0
  - distributed=2022.2.1=pyhd3eb1b0_0
  - docker-py=5.0.3=py39hc1b9086_1
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.8=hbbae597_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.6.0=pyhd8ed1ab_0
  - flask=2.1.1=pyhd8ed1ab_0
  - flatbuffers=1.12.1=h3b9df90_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fontconfig=2.14.0=haba4ffa_0
  - freeglut=3.2.2=h3b9df90_1
  - freetype=2.11.0=h9215f1b_0
  - frozenlist=1.3.0=py39ha810350_0
  - fsspec=2022.3.0=pyhd8ed1ab_0
  - future=0.18.2=py39hc1b9086_5
  - gast=0.4.0=pyh9f0ad1d_0
  - geos=3.8.0=he6710b0_0
  - gettext=0.21.0=h1b965fe_0
  - gflags=2.2.2=1687.g1de4c42
  - giflib=5.2.1=h339bb43_2
  - git=2.35.3=pl5321h131946c_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - glib=2.69.1=h5f94dde_1
  - glob2=0.7=py_0
  - glog=0.5.0=h4040248_0
  - gmock=1.10.0=h15a1290_2
  - gmp=6.2.1=hea85c5d_0
  - gnutls=3.6.13=hb04485b_1
  - google-auth=1.23.0=pyhd8ed1ab_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - googleapis-common-protos=1.56.0=py39hc1b9086_0
  - gorilla=0.4.0=pyhd8ed1ab_0
  - graphite2=1.3.13=hea85c5d_1001
  - greenlet=1.1.2=py39had50986_1
  - grpc-cpp=1.41.0=h01ef132_pb3.14_1
  - grpcio=1.42.0=py39hff9cdcc_0
  - gtest=1.10.0=h15a1290_2
  - gunicorn=20.1.0=py39hc1b9086_1
  - gwcs=0.17.1=pyhd8ed1ab_0
  - h5py=3.2.1=py39hf727584_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf4=4.2.13=h2ab409d_3
  - hdf5=1.10.6=hb1b8bf9_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.8=pyhd3eb1b0_0
  - horovod=0.23.0=cuda11.2_openmpi_py39_1
  - huggingface_hub=0.4.0=pyhd8ed1ab_0
  - hypothesis=6.47.1=pyhd8ed1ab_0
  - icu=58.2=hf484d3e_1000
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2021.8.26=py39h74076e2_0
  - imageio=2.18.0=pyhcf75d05_0
  - imgaug=0.4.0=pyhd8ed1ab_1
  - importlib-metadata=4.11.3=py39hc1b9086_1
  - importlib_metadata=4.11.3=hd8ed1ab_1
  - importlib_resources=5.6.0=pyhd8ed1ab_0
  - ipykernel=6.8.0=py39h0de2273_0
  - ipython=7.32.0=py39hc1b9086_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jansson=2.13.1=h3275034_0
  - jasper=2.0.14=h3e40e2c_2
  - jedi=0.18.1=py39hc1b9086_1
  - jinja2=3.1.1=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h4e0d66e_0
  - jpeg-turbo=2.1.0=heb6caa9_2
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - junit-xml=1.9=pyh9f0ad1d_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hc1b9086_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - jxrlib=1.1=h4e0d66e_2
  - keras=2.7.0=pyh2f7d780_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=hb283c62_0
  - kiwisolver=1.4.2=py39h2bf7372_1
  - krb5=1.19.3=h33c4487_0
  - lame=3.100=h4e0d66e_1001
  - langcodes=3.3.0=pyhccecc47_2
  - lcms2=2.12=h2045e0b_0
  - ld_impl_linux-ppc64le=2.36.1=ha35d02b_2
  - lerc=3.0=h3b9df90_0
  - leveldb=1.20=hf484d3e_1
  - libaec=1.0.6=h3b9df90_0
  - libarchive=3.5.1=hb8455fb_1
  - libbrotlicommon=1.0.9=hb283c62_7
  - libbrotlidec=1.0.9=hb283c62_7
  - libbrotlienc=1.0.9=hb283c62_7
  - libclang=10.0.1=default_hc9b7fb1_0
  - libclang-cpp10=10.0.1=default_hc9b7fb1_0
  - libcurl=7.82.0=h2ae36b4_0
  - libdeflate=1.8=h4e0d66e_0
  - libedit=3.1.20210910=h140841e_0
  - libev=4.33=h6eb9509_1
  - libevent=2.1.10=h97db324_4
  - libffi=3.3=hea85c5d_2
  - libflac=1.3.3=py39_2
  - libgcc-ng=11.2.0=h7698a5e_15
  - libgfortran-ng=7.3.0=h822a55f_1
  - libglu=9.0.0=h3b9df90_1001
  - libgomp=11.2.0=h7698a5e_15
  - libiconv=1.16=h6eb9509_0
  - liblief=0.11.5=h3b9df90_1
  - libllvm10=10.0.1=h6332354_3
  - libllvm11=11.1.0=h6c99497_3
  - libnetcdf=4.8.1=h37953bf_1
  - libnghttp2=1.47.0=h262a72d_0
  - libnsl=2.0.0=h4e0d66e_0
  - libogg=1.3.5=h140841e_1
  - libopenblas=0.3.13=h989ec91_0
  - libopencv=4.5.3=hee98b30_py39_pb3.14_1
  - libopus=1.3.1=h4e0d66e_1
  - libpng=1.6.37=h38e1d09_2
  - libprotobuf=3.14.0=h690f14c_0
  - libsndfile=1.0.31=py39_2
  - libsodium=1.0.18=h6eb9509_1
  - libssh2=1.10.0=ha5a9321_2
  - libstdcxx-ng=11.2.0=habdf983_15
  - libtar=1.2.20=h3275034_1003
  - libthrift=0.15.0=h54f692e_1
  - libtiff=4.2.0=h781710b_0
  - libutf8proc=2.7.0=h4e0d66e_0
  - libuuid=2.32.1=h4e0d66e_1000
  - libvorbis=1.3.7=h3b9df90_0
  - libvpx=1.7.0=hf484d3e_0
  - libwebp=1.2.2=he32dc1f_0
  - libwebp-base=1.2.2=h4e0d66e_1
  - libxcb=1.13=h4e0d66e_1004
  - libxgboost=1.5.1=cpu_2
  - libxml2=2.9.12=hcd9f32a_0
  - libzip=1.8.0=h9499428_1
  - libzlib=1.2.11=hb283c62_1014
  - libzopfli=1.0.3=h3b9df90_0
  - llvmlite=0.38.0=py39h06fb8b6_0
  - lmdb=0.9.29=h29c3540_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h3b9df90_1
  - lzo=2.10=h6eb9509_1000
  - magma=2.5.4=cuda11.2_6
  - mako=1.2.0=pyhd8ed1ab_1
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=2.1.1=py39h9ca6cee_1
  - matplotlib=3.4.3=py39hc1b9086_2
  - matplotlib-base=3.4.3=py39hf26b4c6_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - memory_profiler=0.60.0=pyhd8ed1ab_0
  - mistune=0.8.4=py39ha810350_1005
  - mlflow=1.2.0=py_1
  - more-itertools=8.12.0=pyhd8ed1ab_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.3=py39h148fbab_0
  - msgpack-python=1.0.3=py39h66086b3_0
  - multidict=5.2.0=py39ha810350_1
  - multipledispatch=0.6.0=py39h6ffa863_0
  - murmurhash=1.0.6=py39had50986_2
  - nbclient=0.6.0=pyhd8ed1ab_0
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.3.0=pyhd8ed1ab_0
  - nccl=2.11.4=cuda11.2_1
  - ncurses=6.3=hab78ccb_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf4=1.5.7=py39hf727584_1
  - nettle=3.6=ha07698b_0
  - networkx=2.7.1=pyhd8ed1ab_0
  - nibabel=3.2.2=pyhd8ed1ab_0
  - nomkl=3.0=0
  - notebook=6.4.11=pyha770c72_0
  - numactl=2.0.12=h459fe5f_5
  - numba=0.55.1=py39hd44d982_0
  - numpy=1.20.3=py39hc544b32_0
  - numpy-base=1.20.3=py39h86143a2_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - onnx=1.10.2=h3ec3fa4_py39_pb3.14_1
  - onnxconverter-common=1.9.0=pyh22e41e1_pb3.14_1
  - openblas=0.3.13=h6ffa863_0
  - openblas-devel=0.3.13=h6ffa863_0
  - opencv=4.5.3=py39_pb3.14_1
  - openh264=2.1.1=h690f14c_0
  - openjpeg=2.4.0=h29f4549_1
  - openmpi=4.1.1=h5a6adba_2
  - openssl=1.1.1o=hb283c62_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - orc=1.7.2=h5f26893_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py39h78c9397_0
  - pandoc=2.11=h7557452_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.12.1=pyhd3eb1b0_0
  - param=1.12.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - patchelf=0.14.5=hea85c5d_0
  - pathy=0.6.1=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h3b9df90_0
  - pcre2=10.37=h32277c3_0
  - perl=5.32.1=2_h4e0d66e_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - photutils=1.4.0=py39h4e7300c_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39h3f95422_0
  - pip=22.0.4=pyhd8ed1ab_0
  - pixman=0.38.0=h6eb9509_1003
  - pkginfo=1.8.2=pyhd8ed1ab_0
  - pluggy=0.13.1=py39hc1b9086_4
  - portpicker=1.5.0=pyhd8ed1ab_0
  - powerai-license=1.7.0=786.g73e75a8
  - preshed=3.0.6=py39had50986_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - promise=2.3=py39hc1b9086_5
  - prompt-toolkit=3.0.29=pyha770c72_0
  - protobuf=3.14.0=py39had50986_1
  - psutil=5.9.0=py39ha810350_0
  - pthread-stubs=0.4=h339bb43_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.11.0=pyh6c4a22f_0
  - py-lief=0.11.5=py39h4c72827_1
  - py-opencv=4.5.3=h028a14a_py39_pb3.14_1
  - pyarrow=5.0.0=py39hd42383e_3_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycosat=0.6.3=py39ha810350_1009
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py39h6ffa863_0
  - pydantic=1.8.2=py39ha810350_2
  - pydicom=2.3.0=pyh6c4a22f_0
  - pyerfa=2.0.0=py39h140841e_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pynndescent=0.5.7=pyh6c4a22f_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39h9ca6cee_1
  - pysocks=1.7.1=py39hc1b9086_5
  - pytest=5.4.3=py39h6ffa863_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.7.0=py_0
  - pytest-astropy-header=0.1.2=py_0
  - pytest-doctestplus=0.12.0=pyhd8ed1ab_0
  - pytest-openfiles=0.5.0=py_0
  - pytest-remotedata=0.3.3=pyhd8ed1ab_0
  - python=3.9.12=h836d2c2_0
  - python-clang=10.0.1=default_h1154ca9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python-libarchive-c=3.1=py39hc1b9086_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=cuda11.2_py39_1
  - pytorch-base=1.10.1=h1234567_cuda11.2_py39_pb3.14_1
  - pytz=2022.1=pyhd8ed1ab_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.3.0=py39h4e7300c_1
  - pyyaml=5.4.1=py39ha810350_1
  - pyzmq=22.3.0=py39h82ca517_2
  - querystring_parser=1.2.4=py_0
  - re2=2020.11.01=h29c3540_1
  - readline=8.1.2=h140841e_1
  - regex=2022.3.15=py39h140841e_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - ripgrep=13.0.0=h0cb23b2_2
  - rsa=4.8=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py39ha810350_1006
  - sacremoses=0.0.49=pyhd8ed1ab_0
  - schwimmbad=0.3.2=py39hc1b9086_1
  - scikit-image=0.19.2=py39h6474468_0
  - scikit-learn=1.0.2=py39haab0e66_1
  - scipy=1.7.3=py39he743248_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentencepiece=0.1.96=hb4654e5_py39_pb3.14_1
  - setuptools=60.9.3=py39hc1b9086_0
  - shap=0.40.0=py39h92fcf75_0
  - shapely=1.8.4=py39h61574a3_0
  - shellingham=1.4.0=pyh44b312d_0
  - simplejson=3.17.6=py39ha810350_0
  - six=1.15.0=pyh9f0ad1d_0
  - skl2onnx=1.10.3=pyh22e41e1_pb3.14_2
  - slicer=0.0.7=pyhd8ed1ab_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=hb209c28_3
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - spacy=3.2.1=py39h31502c1_0
  - spacy-legacy=3.0.8=pyhccecc47_4
  - spacy-loggers=1.0.1=pyhccecc47_1
  - sqlalchemy=1.4.35=py39h9ca6cee_0
  - sqlite=3.38.2=hd7247d8_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - srsly=2.4.2=py39had50986_0
  - statsmodels=0.13.2=py39h140841e_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tbb=2021.5.0=h06f31f1_1
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - tensorboard=2.7.0=pyhd04b460_pb3.14_2
  - tensorboard-data-server=0.6.1=pyhb80c3c2_3
  - tensorboard-plugin-wit=1.6.0=pyh9f0ad1d_0
  - tensorflow=2.7.0=cuda11.2_py39_1
  - tensorflow-base=2.7.0=h1234567_cuda11.2_py39_pb3.14_2
  - tensorflow-datasets=4.3.0=pyhd8ed1ab_0
  - tensorflow-estimator=2.7.0=pyhaea4cc0_1
  - tensorflow-io-gcs-filesystem=0.23.1=h974087e_py39_pb3.14_1
  - tensorflow-metadata=1.2.0=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - terminado=0.13.3=py39hc1b9086_1
  - thinc=8.0.12=py39h31502c1_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2021.7.2=pyhd8ed1ab_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h41c6715_0
  - tokenizers=0.10.3=py39h837c7e6_1
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchtext-base=0.11.1=cuda11.2_py39_1
  - torchvision=0.11.2=cuda11.2_py39_1
  - torchvision-base=0.11.2=cuda11.2_py39_1
  - tornado=6.1=py39h9ca6cee_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - transformers=4.16.2=pyhd8ed1ab_0
  - typer=0.4.1=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - umap-learn=0.5.2=py39hc1b9086_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - uwsgi=2.0.20=py39h980472c_0
  - wasabi=0.9.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.2=pyhd8ed1ab_0
  - werkzeug=2.1.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.1=pyh9f0ad1d_3
  - wrapt=1.12.1=py39ha810350_3
  - x264=1!157.20191217=h7b6447c_0
  - xarray=0.20.1=pyhd3eb1b0_1
  - xgboost=1.5.1=cpu_py39_2
  - xorg-fixesproto=5.0=h4e0d66e_1002
  - xorg-inputproto=2.3.2=h4e0d66e_1002
  - xorg-kbproto=1.0.7=h4e0d66e_1002
  - xorg-libice=1.0.10=h4e0d66e_0
  - xorg-libsm=1.2.3=h743bd3d_1000
  - xorg-libx11=1.7.2=h4e0d66e_0
  - xorg-libxau=1.0.9=h4e0d66e_0
  - xorg-libxdmcp=1.1.3=h4e0d66e_0
  - xorg-libxext=1.3.4=h4e0d66e_1
  - xorg-libxfixes=5.0.3=h4e0d66e_1004
  - xorg-libxi=1.7.10=h4e0d66e_0
  - xorg-libxrender=0.9.10=h4e0d66e_1003
  - xorg-renderproto=0.11.1=h4e0d66e_1002
  - xorg-xextproto=7.3.0=h4e0d66e_1002
  - xorg-xproto=7.0.31=h4e0d66e_1007
  - xz=5.2.5=h6eb9509_1
  - yaml=0.2.5=h4e0d66e_2
  - yarl=1.7.2=py39ha810350_0
  - zeromq=4.3.4=h3b9df90_1
  - zfp=0.5.5=h3b9df90_8
  - zict=2.1.0=py39h6ffa863_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=hb283c62_1014
  - zstd=1.4.9=h65c4b1a_0
  - pip:
    - addict==2.4.0
    - apex==0.1
    - autograd==1.4
    - futures==3.0.5
    - gdown==4.6.0
    - mmcv-full==1.5.0
    - ninja==1.11.1
    - peigen==0.0.9
    - proxmin==0.6.12
    - pybind11==2.10.0
    - scarlet==1.0.1+g11d1363
    - sep==1.2.1
    - submitit==1.4.1
    - typing-extensions==4.4.0
    - yapf==0.32.0
prefix: /home/g4merz/.conda/envs/astrodetnv
